mkdocs.yml

Handle deprecation of `mkdocs_material_extensions`.

docs: fix deprecation warning

---

src/safeds_runner/server/main.py

Closes #19
- display version fetched from metadata for --version and -V args (using importlib.metadata.version)

feat: add cli argument to display runner version

---

src/safeds_runner/server/pipeline_manager.py
tests/safeds_runner/server/test_runner_main.py
tests/safeds_runner/server/test_websocket_mock.py

Closes #18
- use spawn instead of fork to not deadlock when running tests

fix: race condition when initializing multiprocessing manager

---

.github/codecov.yml

For some reason, Codecov started to treat some test files as source files. This PR explicitly excludes all test files.

ci: exclude test files from Codecov report

---

src/safeds_runner/server/json_encoder.py
src/safeds_runner/server/main.py
tests/safeds_runner/server/test_json_encoder.py
tests/safeds_runner/server/test_websocket_mock.py

Closes #20 
- added SafeDSEncoder that is used for custom types (tables, images)
- don't crash when unknown types are attempted to be sent, instead send a "\<Not Displayable\>" placeholder value
- added encoding tests + not displayable to existing message exchange

feat: added json serializer that encodes tables and images

---

poetry.lock
pyproject.toml
src/safeds_runner/server/main.py
src/safeds_runner/server/pipeline_manager.py
tests/safeds_runner/server/test_websocket_mock.py

- fix: allow multiple websocket connections in parallel (custom threading / multiprocessing is initialized before patching for use with gevent)
- feat: send events (during execution) to all connected (listening) websocket connections
- Queries (placeholder_query) is still using a request-response pattern and does not multicast to all connections
- green thread pool size for connections is limited to 8 for now

fix: allow multiple connections to work with the runner

---

src/safeds_runner/server/messages.py
src/safeds_runner/server/server.py
tests/safeds_runner/server/test_websocket_mock.py

- changed `placeholder_query` messages (VSCode to Runner) to allow optional `window_begin` and `window_size` fields (in addition to the placeholder `name`)
- change validation to validate correctness of these fields
- changed `placeholder_value` messages (Runner to VSCode) to include `window_begin`, `window_size` and `window_max` fields and `windowed` flag when querying only windows of data

feat: support placeholder queries that only request a subset of data

---

.github/workflows/main.yml
.github/workflows/pr.yml
poetry.lock
pyproject.toml

- restore python 3.12 support, as library now re-enabled support (https://github.com/Safe-DS/Library/pull/536)

build: update to safe-ds 0.18 and re-enable python 3.12

---

src/safeds_runner/__init__.py
src/safeds_runner/server/_pipeline_manager.py
tests/safeds_runner/server/test_memoization.py

Related to https://github.com/Safe-DS/DSL/issues/1013
- introduces a new `memoized_dynamic_call` function, that fetches the callable from the provided instance (receiver), calculates a new fully qualified function name for the dynamic call and forwards everything to the memoization map

fix: dynamic memoization calls

---

poetry.lock
pyproject.toml
src/safeds_runner/server/_memoization_map.py
src/safeds_runner/server/_memoization_stats.py
src/safeds_runner/server/_memoization_strategies.py
src/safeds_runner/server/_memoization_utils.py
src/safeds_runner/server/main.py
tests/safeds_runner/server/test_memoization.py
tests/safeds_runner/server/test_memoization_utils.py

- shared memory
- lazy comparisons
- limited memory 
- value removal strategies
- use deterministic seed for hashing
Closes #44
Depends on https://github.com/Safe-DS/Library/pull/609

feat: memoization improvements

---

poetry.lock
pyproject.toml

Closes partially #85
Require the latest version of `safe-ds`.

feat: bump `safe-ds` to `v0.21.0`

---

src/safeds_runner/server/_pipeline_manager.py
tests/safeds_runner/server/test_memoization.py

Closes #88
`file_mtime` and `absolute_path` can now work with a list of strings as well as a single string. This is needed for function like `ImageList.from_files` that accept multiple paths.
For now, order matters. Specifying the same paths in a different order leads to a different memoization key.

feat: handle list of filenames in `absolute_path` and `file_mtime`

---

src/safeds_runner/server/_json_encoder.py
src/safeds_runner/server/_memoization_map.py
src/safeds_runner/server/_memoization_stats.py
src/safeds_runner/server/_memoization_utils.py
src/safeds_runner/server/_messages.py
src/safeds_runner/server/_module_manager.py
src/safeds_runner/server/_pipeline_manager.py
src/safeds_runner/server/_server.py

Closes #40
We've had a few cases in the past where type hints in the docs and in the code disagreed. Unfortunately, PyCharm prefers the types in the docs in this case, leading to confusion. Now, only the code contains type hints.

docs: remove type hints from docstrings

---

src/safeds_runner/server/_memoization_map.py
src/safeds_runner/server/_memoization_utils.py
src/safeds_runner/server/_pipeline_manager.py
tests/safeds_runner/server/test_memoization.py
tests/safeds_runner/server/test_websocket_mock.py

Related to https://github.com/Safe-DS/DSL/issues/1087
Memoized calls now accept positional and keyword arguments separately.

feat: pass keyword arguments separately in memoized calls

---

poetry.lock
pyproject.toml
src/safeds_runner/server/_json_encoder.py
src/safeds_runner/server/_messages.py
src/safeds_runner/server/_pipeline_manager.py
tests/safeds_runner/memoization/test_memoization_utils.py
tests/safeds_runner/server/test_json_encoder.py
tests/safeds_runner/server/test_pipeline_manager_type_conversion.py
tests/safeds_runner/server/test_websocket_mock.py

* Require `safe-ds` version 0.22.0.
* Handle new `TabularDataset` (former `TaggedTable`).

feat: require `safe-ds` version 0.22.0

---

poetry.lock
pyproject.toml

Use the CUDA version of torch in dev environments on Windows. On Linux, CUDA was already supported previously. On MacOS, CUDA is not available.

build: use CUDA version of torch in dev environment on Windows

---

poetry.lock
pyproject.toml
src/safeds_runner/memoization/_memoization_utils.py
src/safeds_runner/server/_pipeline_manager.py
tests/safeds_runner/memoization/test_memoization_utils.py

Require the latest version of `safe-ds` (0.24.0).

feat: require `safe-ds` version 0.24.0

---

poetry.lock
pyproject.toml
src/safeds_runner/server/_messages.py

Require the latest version of `safe-ds` (0.25.0).

feat: require `safe-ds` version 0.25.0

---

.github/workflows/main.yml
.github/workflows/pr.yml

Don't run tests on Windows/MacOS and Python 3.11 to not overload the cache.

ci: exclude two matrix configurations

---

poetry.lock
pyproject.toml

Require the latest version of `safe-ds` (0.28.0).

feat: require `safe-ds` version 0.28.0

---

src/safeds_runner/server/_json_encoder.py
src/safeds_runner/server/_server.py
tests/safeds_runner/server/test_websocket_mock.py

Convert a value to a string by default using its `__str__` method, instead of sending the constant string `"<Not displayable>"`.

fix: show more useful value than "not displayable"

---

src/safeds_runner/server/_json_encoder.py
tests/safeds_runner/server/test_json_encoder.py
tests/safeds_runner/server/test_websocket_mock.py

By default, the `dumps` method of Python's `json` module generates invalid JSON for non-finite floats (NaN, +/- Infinity). We now convert them to a string instead. For tables, we still replace them with nulls as before to avoid mixed data.
If we later use a binary format to transfer the table data, we won't need to replace these values in tables anymore.

fix: encoding of non-finite floats
